#pragma once

#define OPEN_TIME 25
#define CLOSE_TIME 25
#define CYCLE_TIME OPEN_TIME + CLOSE_TIME

#define VISITORS_LIMIT 50

#define GUIDES_NUMBER 5
#define GROUP_SIZE 7
#define GUIDES_GATHER_WAIT 5
#define GUIDES_GATHER_CHECK_INTERVAL 0.2
#define GUIDES_MOVETIME_MIN 1
#define GUIDES_MOVETIME_MAX 2

#define BRIDGE_LIMIT 5
#define TOWER_LIMIT 10
#define FERRY_LIMIT 6

#define VISITOR_SPAWN_MIN_INTERVAL 0.5
#define VISITOR_SPAWN_MAX_INTERVAL 2
#define VIP_CHANCE 0.2

#define KIDS_CHANCE 0.35
#define KIDS_LIMIT 4

#define TICKET_PRICE 2
#define TICKET_SALE_TIME 0.1