#pragma once

#define OPEN_TIME 1
#define CLOSE_TIME 1
#define CYCLE_TIME OPEN_TIME + CLOSE_TIME

#define VISITORS_LIMIT 100

#define GUIDES_NUMBER 5
#define GROUP_SIZE 7
#define GUIDES_GATHER_WAIT 0
#define GUIDES_GATHER_CHECK_INTERVAL 0
#define GUIDES_MOVETIME_MIN 0
#define GUIDES_MOVETIME_MAX 0

#define BRIDGE_LIMIT 6
#define BRIDGE_CROSS_MIN_TIME 0
#define BRIDGE_CROSS_MAX_TIME 0

#define TOWER_LIMIT 10
#define TOWER_ACTION_MIN_TIME 0
#define TOWER_ACTION_MAX_TIME 0

#define FERRY_LIMIT 10
#define FERRY_VOYAGE_TIME 0

#define VISITOR_SPAWN_MIN_INTERVAL 0
#define VISITOR_SPAWN_MAX_INTERVAL 0
#define VIP_CHANCE 0

#define KIDS_CHANCE 0.35
#define KIDS_LIMIT 4

#define TICKET_PRICE 2
#define TICKET_SALE_TIME 0